opensourceways/infra-common

- common-applications/control/argocd/ingress.yaml
- common-applications/control/argocd/kustomization.yaml
- common-applications/control/argocd/secrets.yaml
replace domain name certificate(one year)
> replace domain name certificate

- common-applications/control/cla/deployment.yaml
- common-services/argo-notifications/install.yaml
> Create folder before start command

- common-applications/om/om-webserver/deployment.yaml
> add redis service

- common-applications/om/om-webserver/deployment.yaml
> update version to 1.0.5

- common-applications/om/om-collect/mindspore/cla/kustomization.yaml
- common-applications/om/om-collect/mindspore/gitee/kustomization.yaml
- common-applications/om/om-collect/openeuler/cla/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee/kustomization.yaml
- common-applications/om/om-collect/opengauss/cla/kustomization.yaml
- common-applications/om/om-collect/opengauss/gitee/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee/kustomization.yaml
> update cla version

- common-applications/om/om-collect/openeuler/cve/deploy.json
- common-applications/om/om-collect/openeuler/cve/kustomization.yaml
- common-applications/om/om-collect/openeuler/cve/secrets.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
> add cve pod

- common-applications/om/om-collect/openeuler/cve/kustomization.yaml
> cve bug fix

- common-applications/om/om-collect/openeuler/cve/kustomization.yaml
> cve dashboard bug fix

- common-applications/om/om-collect/mindspore/cla/kustomization.yaml
- common-applications/om/om-collect/openeuler/cla/kustomization.yaml
- common-applications/om/om-collect/opengauss/cla/kustomization.yaml
> update cla version to 0.0.81

- common-applications/control/jenkins-slave/kustomization.yaml
- common-applications/control/jenkins-slave/license-check-slave.yaml
add a slave node for license compliance check
> add a slave node for license compliance check

- common-applications/control/jenkins-slave/license-check-slave.yaml
> fix image name

- common-applications/control/cloudsca/analysis.yaml
- common-applications/control/cloudsca/dm.yaml
- common-applications/control/cloudsca/eureka.yaml
- common-applications/control/cloudsca/gateway.yaml
- common-applications/control/cloudsca/web.yaml
update apiVersion of control/cloudsca
> update apiVersion of sca

- common-applications/control/cloudsca/analysis.yaml
- common-applications/control/cloudsca/dm.yaml
- common-applications/control/cloudsca/eureka.yaml
- common-applications/control/cloudsca/gateway.yaml
update image of cloudsca deploy:eureka/gateway/analysis/dm
> update image of cloudsca deploy

- common-applications/control/cloudsca/analysis.yaml
- common-applications/control/cloudsca/dm.yaml
- common-applications/control/cloudsca/gateway.yaml
update image of sca deploy analysis/dm/gateway
> update image of sca deploy analysis/dm/gateway

- common-applications/control/cloudsca/analysis.yaml
update image of cloudsca analysis deploy 
fix typo of sca-analysis service name
> update image of cloudsca analysis and fix analysis service typo

- common-applications/om/om-collect/mindspore/git_commit/kustomization.yaml
update git_commit version to 0.1.7
> update git_commit version to 0.1.7

- common-applications/om/om-collect/openeuler/gitee/kustomization.yaml
> update openeuler gitee version to 0.1.15

- common-applications/om/om-webserver/deployment.yaml
> update om-webserver version to 0.0.30

- common-applications/om/om-collect/openeuler/gitee-event-repo-log/deploy.json
- common-applications/om/om-collect/openeuler/gitee-event-repo-log/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee-event-repo-log/secrets.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
build gitee-event-repo-log service
> build gitee-event-repo-log service

- common-services/image-secret-patcher/deployment.yaml
- common-services/image-secret-patcher/kustomization.yaml
- common-services/image-secret-patcher/namespace.yaml
- common-services/image-secret-patcher/rbac.yaml
- common-services/image-secret-patcher/secret.yaml
Add raw image secret patch service
> [private image]Add raw image secret patch service

- common-services/vault/install-0.4.0.yaml
> Make vault image private

- common-applications/control/mail/config.yaml
- common-services/argo-notifications/install.yaml
- common-services/argocd/install.yaml
- common-services/metric-server/components.yaml
- common-services/nginx-ingress/default-backend.yaml
these images are made private
1. argocd
2. metrics-server
3. default nginx backend
> Private argocd images

- common-services/cert-manager-legacy/cert-manager.yaml
- common-services/cert-manager/cert-manager.yaml
Make cert-manager images private
> Private cert-manager images

- common-applications/om/om-collect/mindspore/github-star/deploy.json
- common-applications/om/om-collect/mindspore/github-star/kustomization.yaml
- common-applications/om/om-collect/mindspore/github-star/secrets.yaml
> build github-star service

- common-applications/om/om-collect/mindspore/github-star/kustomization.yaml
update image version to 0.1.43
> upgrade github-star-om-collect image version to 0.1.43

- common-applications/om/om-collect/mindspore/huawei_swr/deploy.json
- common-applications/om/om-collect/mindspore/huawei_swr/kustomization.yaml
- common-applications/om/om-collect/mindspore/huawei_swr/secrets.yaml
update image version to 0.1.49
> deploy swr download statistic service

- common-applications/om/om-collect/kunpeng/git_commit/kustomization.yaml
update image version to 0.1.50
> update image version to 0.1.50

- common-applications/control/cloudsca/api-gateway.yaml
change api-gateway deploy image to avoid conflict with gateway
> change api-gateway deploy image

- common-applications/control/cloudsca/api-gateway.yaml
change image secret of api-gateway
> change image secretof api-gateway

- common-applications/control/argocd/oauth-proxy.yaml
- common-applications/control/cloudsca/oauth-proxy.yaml
- common-applications/control/grafana/oauth-proxy.yaml
- common-applications/control/jenkins/oauth-proxy.yaml
- common-applications/control/kibana/oauth-proxy.yaml
- common-applications/control/maintenance/oauth-proxy.yaml
- common-applications/control/om-grafana-ingress/oauth-proxy.yaml
- common-applications/control/vault/oauth-proxy.yaml
upgrade oauth proxy to support customize sign in logo
> Upgrade oauth proxy

- common-applications/om/om-webserver/deployment.yaml
update openlookeng users api that users equals package download count
> update om-webserver version to 0.0.42

- common-applications/om/om-collect/openeuler/cve/kustomization.yaml
update cve_rec_duration calculation by CVE_vtopic_rec_time if CVE_vtopic_rec_time exist
> update openeuler cve version to 0.1.62

- common-applications/om/om-collect/mindspore/account_org/kustomization.yaml
- common-applications/om/om-collect/openeuler/account_org/kustomization.yaml
- common-applications/om/om-collect/opengauss/account_org/kustomization.yaml
update email->giteeid source that from es,before be from csv
> update account_org version to 0.1.64

- common-applications/om/om-collect/openlookeng/kustomization.yaml
- common-applications/om/om-collect/openlookeng/tryme/deploy.json
- common-applications/om/om-collect/openlookeng/tryme/kustomization.yaml
- common-applications/om/om-collect/openlookeng/tryme/secrets.yaml
add openlookeng tryme data collection
> add openlookeng tryme

- common-applications/om/om-collect/openeuler/googleanalytic-user/deploy.json
- common-applications/om/om-collect/openeuler/googleanalytic-user/kustomization.yaml
- common-applications/om/om-collect/openeuler/googleanalytic-user/secrets.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
update image version to 0.1.66
> add google-user service

- common-applications/om/om-collect/openlookeng/tryme/kustomization.yaml
change getting github_login by name to getting by id
> update openlookeng tryme version to 0.1.67

- common-applications/om/om-collect/openeuler/googleanalytic-user/kustomization.yaml
update kustomization.yaml 
modification: update project version from 0.1.66 to 0.1.68
> Fix the exception that service start failure

- common-applications/om/om-collect/openeuler/googleanalytic-user/kustomization.yaml
add discrepency package correctly in Dockerfile, then update the project version from 0.1.68 to 0.1.69
> Fixed googleanalytic service startup failure

- common-applications/om/om-collect/openeuler/googleanalytic-user/kustomization.yaml
update project version to 0.1.70
> Fix googleanalytic service startup exception with correct request_body path

- common-services/cert-manager-legacy/cert-manager.yaml
- common-services/cert-manager/cert-manager.yaml
Change acmesolver image from quay.io to huawei  SWR.
> Change acmesolver image to swr

- common-applications/om/om-collect/openeuler/googleanalytic-user/deploy.json
- common-applications/om/om-collect/openeuler/googleanalytic-user/secrets.yaml
Modified request_body filename in deploy.json and scretes.yaml
> Fixed googleanalytic service startup failure result in falling to find out openeuler_googleanalytic_request_body.json 

- common-applications/om/om-collect/openeuler/googleanalytic-user/deploy.json
correct request_body name's error in deploy.json
> Fixed google service startup exception with mount file error

- common-applications/openeuler-hk/ingress/service.yaml
- common-applications/openeuler-hk/ingress/tcp_configmap.yaml
Reverts opensourceways/infra-common#380
> Revert "Add ports open for openeuler-oqserver"

- common-applications/om/om-collect/kunpeng/git_commit/kustomization.yaml
modified the way of get the names from branches in a repository.
upgrade version to 0.1.71
> fix git_commit service  git execute error

- common-applications/om/om-collect/openeuler/git_commit/deploy.json
- common-applications/om/om-collect/openeuler/git_commit/kustomization.yaml
- common-applications/om/om-collect/openeuler/git_commit/secrets.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
- common-applications/om/om-collect/opengauss/git_commit/deploy.json
- common-applications/om/om-collect/opengauss/git_commit/kustomization.yaml
- common-applications/om/om-collect/opengauss/git_commit/secrets.yaml
The newest version of git-commit service add a funciton that fetch repo from various sources automatically.
> startup git-commit service for openeuler and update newest version for opengauss

- common-applications/om/om-collect/kunpeng/git_commit/kustomization.yaml
and add a repo remove duplication
> Fix the bug cannot fetch repos from json file in git_commit.py

- common-applications/om/om-webserver/deployment.yaml
> format yaml

- common-applications/om/om-collect/openeuler/kustomization.yaml
- common-applications/om/om-collect/openeuler/up-download-ratio/deploy.json
- common-applications/om/om-collect/openeuler/up-download-ratio/kustomization.yaml
- common-applications/om/om-collect/openeuler/up-download-ratio/secrets.yaml
add week and month changes ratio
> add up down ratio

- common-applications/om/om-collect/openeuler/cve/kustomization.yaml
> update cve version to 0.2.2

- common-applications/om/om-collect/kunpeng/git_commit/kustomization.yaml
- common-applications/om/om-collect/kunpeng/git_commit_all/kustomization.yaml
- common-applications/om/om-collect/mindspore/git_commit/kustomization.yaml
- common-applications/om/om-collect/openeuler/git_commit/kustomization.yaml
- common-applications/om/om-collect/openeuler/googleanalytic-user/kustomization.yaml
- common-applications/om/om-collect/opengauss/git_commit/kustomization.yaml
- common-applications/om/om-collect/openlookeng/git_commit/kustomization.yaml
modified base_url of git_commit service;
add increment module of googleanalytic_user service;
> Update git_commit & googleanalytic_user services

- common-applications/om/om-webserver/deployment.yaml
> update om-webserver version from 0.0.43 to 0.0.44

- common-applications/om/om-collect/ascend/gitee/kustomization.yaml
version is too old,update to 0.1.94
> update ascend gitee version to 0.1.94

- common-applications/control/cla-test/ingress.yaml
修改测试环境nginx的资源安全策略Content-Security-Policy
> set content security policy

- common-applications/om/om-collect/openeuler/git_commit/kustomization.yaml
Fix the bug which cannot get repos completely from Gitee
Add a new function: find out contributor and reviewer from commit body of git_commit service
Change the way of generating record id of each commit
Fix the bug of created_at time of each commit
Other code optimization of git_commit
>  Optimized git_commit.py and github.py

- common-applications/om/om-collect/openeuler/up-download-ratio/kustomization.yaml
> update up_down_ratio version to 0.2.18

- common-applications/control/cla-test/ingress.yaml
- common-applications/control/cla/ingress.yaml
> set cla nginx config

- common-applications/om/om-collect/openeuler/kustomization.yaml
- common-applications/om/om-collect/openeuler/obs_build_averagetime/deploy.json
- common-applications/om/om-collect/openeuler/obs_build_averagetime/kustomization.yaml
- common-applications/om/om-collect/openeuler/obs_build_averagetime/secrets.yaml
calc obs building average time each month
> add obs-build-averagetime server

- common-applications/om/om-collect/openeuler/kustomization.yaml
rename resources "obs-build-averagetime" to "obs_build_averagetime"
> update obs_build_averagetime resource name

- common-applications/om/om-collect/openlookeng/gitee-star/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee/kustomization.yaml
> update gitee and gitee_star version to 0.2.28

- common-applications/om/om-collect/mindspore/gitee/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee/kustomization.yaml
- common-applications/om/om-collect/opengauss/gitee/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee/kustomization.yaml
update http request error message
> Fix gitee repo cannot get in gitee resource

- common-applications/om/om-collect/mindspore/collect-data/kustomization.yaml
- common-applications/om/om-collect/openlookeng/collect-data/kustomization.yaml
update using regex extraction time
> update openlookeng/mindspore collect-data version to 0.2.34

- common-applications/om/om-collect/openeuler/issue_rule_label/deploy.json
- common-applications/om/om-collect/openeuler/issue_rule_label/kustomization.yaml
- common-applications/om/om-collect/openeuler/issue_rule_label/secrets.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
- common-applications/om/om-collect/openeuler/prophet_prediction/deploy.json
- common-applications/om/om-collect/openeuler/prophet_prediction/kustomization.yaml
- common-applications/om/om-collect/openeuler/prophet_prediction/secrets.yaml
add issue_rule_label && prophet_prediction
> add issue_rule_label && prophet_prediction

- common-applications/om/om-collect/openeuler/issue_rule_label/kustomization.yaml
- common-applications/om/om-collect/openeuler/prophet_prediction/kustomization.yaml
add hanllp,nltk,pandas,pystan,prophet to requirements.txt
> add hanllp,nltk,pandas,pystan,prophet to requirements.txt

- common-applications/om/om-collect/openeuler/issue_rule_label/kustomization.yaml
- common-applications/om/om-collect/openeuler/prophet_prediction/kustomization.yaml
> update yaml load to safe load

- common-applications/om/om-collect/openeuler/issue_rule_label/deployment.yaml
- common-applications/om/om-collect/openeuler/issue_rule_label/kustomization.yaml
- common-applications/om/om-collect/openeuler/prophet_prediction/deployment.yaml
- common-applications/om/om-collect/openeuler/prophet_prediction/kustomization.yaml
add resources memory for prophet_prediction and issue_rule_label
> add resources memory for prophet_prediction and issue_rule_label

- common-applications/om/om-collect/ascend/gitee-star/kustomization.yaml
ascend gitee-star image:0.1.26 is not found,update version to 0.2.49
> ascend gitee-star image:0.1.26 is not found

- common-applications/control/playground-manager/deployment.yaml
- common-applications/control/playground-manager/ingress.yaml
- common-applications/control/playground-manager/kustomization.yaml
- common-applications/control/playground-manager/namespace.yaml
- common-applications/control/playground-manager/secrets.yaml
- common-applications/control/playground-manager/service.yaml
Increase the deployment configuration file of playground-manager, the included yaml files are:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- ingress.yaml
- kustomization.yaml
> Increase the deployment configuration file of playground-manager

- common-applications/om/om-collect/openeuler/up-download-ratio/kustomization.yaml
update image version to base version
> update image version to base version

- common-applications/om/om-collect/openeuler/git/deployment.yaml
> add nodeSelector

- common-applications/om/om-collect/openeuler/issue_rule_label/deployment.yaml
- common-applications/om/om-collect/openeuler/issue_rule_label/kustomization.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
- common-applications/om/om-collect/openeuler/prophet_prediction/deployment.yaml
- common-applications/om/om-collect/openeuler/prophet_prediction/kustomization.yaml
> add nodeSelector for update issue_rule_label and prophet_prediction

- common-applications/om/om-collect/openeuler/git/deployment.yaml
- common-applications/om/om-collect/openeuler/issue_rule_label/deployment.yaml
- common-applications/om/om-collect/openeuler/issue_rule_label/kustomization.yaml
- common-applications/om/om-collect/openeuler/prophet_prediction/deployment.yaml
- common-applications/om/om-collect/openeuler/prophet_prediction/kustomization.yaml
When the user_df is less than 2, clear single user events
> When the user_df is less than 2, clear single user events

- common-applications/om/om-collect/mindspore/kustomization.yaml
- common-applications/om/om-collect/mindspore/user-relation/deploy.json
- common-applications/om/om-collect/mindspore/user-relation/kustomization.yaml
- common-applications/om/om-collect/mindspore/user-relation/secrets.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
- common-applications/om/om-collect/openeuler/user-relation/deploy.json
- common-applications/om/om-collect/openeuler/user-relation/kustomization.yaml
- common-applications/om/om-collect/openeuler/user-relation/secrets.yaml
- common-applications/om/om-collect/opengauss/kustomization.yaml
- common-applications/om/om-collect/opengauss/user-relation/deploy.json
- common-applications/om/om-collect/opengauss/user-relation/kustomization.yaml
- common-applications/om/om-collect/opengauss/user-relation/secrets.yaml
- common-applications/om/om-collect/openlookeng/kustomization.yaml
- common-applications/om/om-collect/openlookeng/user-relation/deploy.json
- common-applications/om/om-collect/openlookeng/user-relation/kustomization.yaml
- common-applications/om/om-collect/openlookeng/user-relation/secrets.yaml
add issue and pr user collaboration. openeuler,opengauss,openlookeng,mindspore
> add issue and pr user collaboration

- common-applications/om/om-collect/kunpeng/gitee_github_combine/deploy.json
- common-applications/om/om-collect/kunpeng/gitee_github_combine/kustomization.yaml
- common-applications/om/om-collect/kunpeng/gitee_github_combine/secrets.yaml
- common-applications/om/om-collect/kunpeng/kustomization.yaml
gitee and github star fork count collect
> gitee_github_combine star fork count collect

- common-applications/om/om-collect/kunpeng/gitee_github_combine/kustomization.yaml
update gitee_github_combine version to 0.2.68
> change yaml load to safe load

- common-applications/om/om-webserver/deployment.yaml
- common-applications/om/om-webserver/secrets.yaml
add community star fork count api
> add community star fork count api

- common-applications/om/om-webserver/deployment.yaml
add token api and cve details api
> add token api and cve details api

- common-applications/om/om-collect/openeuler/gitee/kustomization.yaml
add issue_state field for gitee issue
> add issue_state field for gitee issue

- common-applications/om/om-collect/openeuler/cve/kustomization.yaml
add issue_customize_state for cve
> add issue_customize_state for cve

- common-applications/om/om-collect/openeuler/cve/kustomization.yaml
format cve vtopic_rec_time to yyyy-MM-dd HH:mm:ss
> format cve vtopic_rec_time

- common-applications/control/playground-manager/deployment.yaml
Modify the template file to the official path
> Modify the template file to the official path

- common-applications/om/om-collect/openeuler/gitee_developer/deploy.json
- common-applications/om/om-collect/openeuler/gitee_developer/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee_developer/secrets.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
collect committer giteeid and email
> add gitee developer info collection

- common-applications/om/om-collect/kunpeng/blue_zone_user/kustomization.yaml
filter commit that is_merged is 1
> filter commit that is_merged is 1

- common-applications/om/om-kafka/openeuler/obs-job-history/kustomization.yaml
- common-applications/om/om-kafka/openeuler/obs-status-summary/kustomization.yaml
- common-applications/om/om-kafka/openeuler/package-status/kustomization.yaml
- common-applications/om/om-kafka/openeuler/statewall-ci-ac/kustomization.yaml
- common-applications/om/om-kafka/openeuler/statewall-dist-build-time/kustomization.yaml
change log4j version to 2.17.0
> change log4j version to 2.17.0

- common-applications/om/om-webserver/deployment.yaml
- common-applications/om/om-webserver/secrets.yaml
> add 2022 new year data api

- common-applications/om/om-webserver/secrets.yaml
change 2022 new year data file
> change 2022 new year data file

- common-applications/om/om-webserver/deployment.yaml
- common-applications/om/om-webserver/secrets.yaml
change newYear api param user to required
> change newYear api param user to required

- common-applications/om/om-webserver/secrets.yaml
> change openlookeng csv path

- common-applications/om/om-webserver/deployment.yaml
- common-applications/om/om-webserver/secrets.yaml
> write new year api user info to ES

- common-applications/om/om-webserver/deployment.yaml
> change new year api user`s id

- common-applications/om/om-collect/mindspore/download/kustomization.yaml
- common-applications/om/om-collect/openeuler/download/kustomization.yaml
- common-applications/om/om-collect/opengauss/download/kustomization.yaml
- common-applications/om/om-collect/openlookeng/download/kustomization.yaml
add package_version for obs download
> add package_version for obs download

- common-applications/om/om-collect/ascend/git-commit-log/deployment.yaml
- common-applications/om/om-collect/ascend/git-commit-log/kustomization.yaml
- common-applications/om/om-collect/ascend/git-commit-log/pvc.yaml
- common-applications/om/om-collect/ascend/git-commit-log/secrets.yaml
- common-applications/om/om-collect/ascend/kustomization.yaml
> add git commit info

- common-applications/om/om-collect/ascend/git-commit-log/deployment.yaml
- common-applications/om/om-collect/ascend/git-commit-log/kustomization.yaml
- common-applications/om/om-collect/ascend/git-commit-log/pvc.yaml
- common-applications/om/om-collect/ascend/git-commit-log/secrets.yaml
add PersistentVolumeClaim for git commit log
> add PersistentVolumeClaim for git commit log

- common-applications/om/om-collect/ascend/git-commit-log/deployment.yaml
- common-applications/om/om-collect/ascend/git-commit-log/pvc.yaml
change PersistentVolumeClaim name to lower case
> change PersistentVolumeClaim name to lower case

- common-applications/om/om-collect/ascend/git-commit-log/deployment.yaml
- common-applications/om/om-collect/ascend/git-commit-log/pvc.yaml
change PersistentVolumeClaim storageClassName to csi-nas
> change PersistentVolumeClaim storageClassName to csi-nas

- common-applications/om/om-collect/ascend/git-commit-log/deployment.yaml
split commits to merge_commits and no_merge_commits
> split commits to merge_commits and no_merge_commits

- common-applications/om/om-collect/kunpeng/git-commit-log/deployment.yaml
> remove redundant ';'

- common-applications/om/om-collect/ascend/git-commit-log/pvc.yaml
- common-applications/om/om-collect/kunpeng/git-commit-log/pvc.yaml
- common-applications/om/om-collect/mindspore/git-commit-log/pvc.yaml
- common-applications/om/om-collect/openeuler/git-commit-log/pvc.yaml
- common-applications/om/om-collect/opengauss/git-commit-log/pvc.yaml
- common-applications/om/om-collect/openlookeng/git-commit-log/pvc.yaml
change storageClassName from csi-nas to csi-disk-SSD
> change storageClassName from csi-nas to csi-disk-SSD

- common-applications/om/om-collect/ascend/git-commit-log/deployment.yaml
- common-applications/om/om-collect/kunpeng/git-commit-log/deployment.yaml
- common-applications/om/om-collect/kunpeng/kustomization.yaml
- common-applications/om/om-collect/kunpeng/white-commit-log/deployment.yaml
- common-applications/om/om-collect/kunpeng/white-commit-log/kustomization.yaml
- common-applications/om/om-collect/kunpeng/white-commit-log/pvc.yaml
- common-applications/om/om-collect/kunpeng/white-commit-log/secrets.yaml
- common-applications/om/om-collect/mindspore/git-commit-log/deployment.yaml
- common-applications/om/om-collect/openeuler/git-commit-log/deployment.yaml
- common-applications/om/om-collect/opengauss/git-commit-log/deployment.yaml
- common-applications/om/om-collect/openlookeng/git-commit-log/deployment.yaml
add white box git commit collection
> add white box git commit collection

- common-applications/om/om-collect/ascend/git-commit-log/deployment.yaml
- common-applications/om/om-collect/kunpeng/git-commit-log/deployment.yaml
- common-applications/om/om-collect/kunpeng/white-commit-log/deployment.yaml
- common-applications/om/om-collect/mindspore/git-commit-log/deployment.yaml
- common-applications/om/om-collect/openeuler/git-commit-log/deployment.yaml
- common-applications/om/om-collect/opengauss/git-commit-log/deployment.yaml
- common-applications/om/om-collect/openlookeng/git-commit-log/deployment.yaml
remote pull can not used by tag branch
> change remote pull to git pull

- common-applications/om/om-collect/openeuler/activities-practice/deploy.json
- common-applications/om/om-collect/openeuler/activities-practice/kustomization.yaml
- common-applications/om/om-collect/openeuler/activities-practice/secrets.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
add openeuler activities_practice data collection
> add openeuler activities_practice data collection

- common-applications/om/om-collect/openeuler/activities-practice/deploy.json
- common-applications/om/om-collect/openeuler/activities-practice/kustomization.yaml
> change score to int

- common-applications/om/om-collect/kunpeng/kustomization.yaml
- common-applications/om/om-collect/kunpeng/upstream-commit-log/deployment.yaml
- common-applications/om/om-collect/kunpeng/upstream-commit-log/kustomization.yaml
- common-applications/om/om-collect/kunpeng/upstream-commit-log/pvc.yaml
- common-applications/om/om-collect/kunpeng/upstream-commit-log/secrets.yaml
add upstream repos commits collection
> add upstream repos commits collection

- common-applications/om/om-collect/kunpeng/upstream-commit-log/deployment.yaml
get company by domain for upstream repos commits
> get company by domain for upstream repos commits

- common-applications/om/om-collect/openeuler/kustomization.yaml
> remove gitee-issue server

- common-applications/om/om-collect/openeuler/gitee-issue/kustomization.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
add issue_state for gitee-issue server
> add issue_state for gitee-issue server

- common-applications/om/om-collect/openeuler/activities-practice/kustomization.yaml
Remove support for anything other than .xls files.  after version 2.0.0
> change xlrd version from 2.0.1 to 1.2.0

- common-applications/om/om-collect/openeuler/gitee-event/kustomization.yaml
overwrite gitee event collection
> overwrite gitee event collection

- common-applications/om/om-collect/mindspore/polymerization-download-ip/kustomization.yaml
- common-applications/om/om-collect/mindspore/polymerization-download/kustomization.yaml
- common-applications/om/om-collect/mindspore/polymerization/kustomization.yaml
- common-applications/om/om-collect/openeuler/polymerization-download-ip/kustomization.yaml
- common-applications/om/om-collect/openeuler/polymerization-download/kustomization.yaml
- common-applications/om/om-collect/openeuler/polymerization/kustomization.yaml
- common-applications/om/om-collect/opengauss/polymerization-download/kustomization.yaml
- common-applications/om/om-collect/opengauss/polymerization/kustomization.yaml
- common-applications/om/om-collect/openlookeng/polymerization-download/kustomization.yaml
- common-applications/om/om-collect/openlookeng/polymerization-github/kustomization.yaml
- common-applications/om/om-collect/openlookeng/polymerization/kustomization.yaml
update user_login to user_id of Polymerization
> update user_login to user_id of Polymerization

- common-applications/om/om-collect/mindspore/gitee/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee/kustomization.yaml
- common-applications/om/om-collect/opengauss/gitee/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee/kustomization.yaml
> add pr_title for gitee collections

- common-applications/om/om-webserver/deployment.yaml
add commit count for om-webserver starFork
> add commit count for om-webserver starFork

- common-applications/om/om-collect/kunpeng/gitee_github_combine/kustomization.yaml
if commit_count is zero, then calc total count error
> gitee api return commit_count zore

- common-applications/om/om-collect/kunpeng/tag-removed-gitee/kustomization.yaml
- common-applications/om/om-webserver/deployment.yaml
set http request timeout to check issue exist
> set http request timeout to check issue exist

- common-applications/om/om-webserver/deployment.yaml
add isoBuildTimes and sigDetails api
> add isoBuildTimes and sigDetails api

- common-applications/om/om-webserver/deployment.yaml
add CompanyContributors and UserContributors API
> add CompanyContributors and UserContributors API

- common-applications/om/om-collect/kunpeng/blue_zone_user/kustomization.yaml
- common-applications/om/om-collect/kunpeng/git-commit-log/deployment.yaml
add all repo getting default branch data for kunpeng
> add all repo getting default branch data for kunpeng

- common-applications/om/om-webserver/deployment.yaml
> update query all api

- common-applications/om/om-collect/kunpeng/tag-removed-gitee/kustomization.yaml
- common-applications/om/om-collect/mindspore/gitee-star/kustomization.yaml
- common-applications/om/om-collect/mindspore/gitee/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee-issue/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee-star/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee/kustomization.yaml
- common-applications/om/om-collect/opengauss/gitee-star/kustomization.yaml
- common-applications/om/om-collect/opengauss/gitee/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee-star/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee/kustomization.yaml
update tag removed repos of gitee
> update tag removed repos of gitee

- common-applications/om/om-collect/openeuler/collect-data/kustomization.yaml
- common-applications/om/om-webserver/deployment.yaml
add maintainer`s gitee_id and email for sig details
> add maintainer`s gitee_id and email for sig details

- common-applications/om/om-webserver/deployment.yaml
> update company name

- common-applications/om/om-kafka/openeuler/kustomization.yaml
- common-applications/om/om-kafka/openeuler/statewall-ci-mistake/deploy.json
- common-applications/om/om-kafka/openeuler/statewall-ci-mistake/kustomization.yaml
- common-applications/om/om-kafka/openeuler/statewall-ci-mistake/secrets.yaml
- common-applications/om/om-kafka/openeuler/statewall-ci-result/deploy.json
- common-applications/om/om-kafka/openeuler/statewall-ci-result/kustomization.yaml
- common-applications/om/om-kafka/openeuler/statewall-ci-result/secrets.yaml
add openeuler ci result and mistake
> add openeuler ci result and mistake

- common-applications/om/om-collect/openeuler/collect-data/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee-event/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee_developer/kustomization.yaml
> add http response code check

- common-applications/om/om-webserver/deployment.yaml
add openeuler 22.03 lts user`s contribute
> add openeuler 22.03 lts user`s contribute

- common-applications/playground/manage-x86-hk/daemonset.yaml
daemonset adds pod-conf environment variable parameter
> daemonset adds pod-conf environment variable parameter

- common-applications/om/om-collect/ascend/git-commit-log-foundation/deployment.yaml
- common-applications/om/om-collect/ascend/git-commit-log-foundation/kustomization.yaml
- common-applications/om/om-collect/ascend/git-commit-log-foundation/pvc.yaml
- common-applications/om/om-collect/ascend/git-commit-log-foundation/secrets.yaml
- common-applications/om/om-collect/ascend/gitee-foundation/deploy.json
- common-applications/om/om-collect/ascend/gitee-foundation/kustomization.yaml
- common-applications/om/om-collect/ascend/gitee-foundation/secrets.yaml
- common-applications/om/om-collect/ascend/kustomization.yaml
add gitee and commit for foundation-models
> add gitee and commit for foundation-models

- common-applications/om/om-collect/openeuler/polymerization/kustomization.yaml
update setToltalCount() and setFirstItem() in for polymerization
> update setToltalCount() and setFirstItem() in for polymerization

- common-applications/om/om-collect/openeuler/kustomization.yaml
- common-applications/om/om-collect/openeuler/refresh_token/deploy.json
- common-applications/om/om-collect/openeuler/refresh_token/kustomization.yaml
- common-applications/om/om-collect/openeuler/refresh_token/secrets.yaml
> Add function: refresh token

- common-applications/om/om-collect/mindspore/gitee-metrics/deploy.json
- common-applications/om/om-collect/mindspore/gitee-metrics/kustomization.yaml
- common-applications/om/om-collect/mindspore/gitee-metrics/secrets.yaml
- common-applications/om/om-collect/mindspore/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee-metrics/deploy.json
- common-applications/om/om-collect/openeuler/gitee-metrics/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee-metrics/secrets.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
- common-applications/om/om-collect/opengauss/gitee-metrics/deploy.json
- common-applications/om/om-collect/opengauss/gitee-metrics/kustomization.yaml
- common-applications/om/om-collect/opengauss/gitee-metrics/secrets.yaml
- common-applications/om/om-collect/opengauss/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee-metrics/deploy.json
- common-applications/om/om-collect/openlookeng/gitee-metrics/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee-metrics/secrets.yaml
- common-applications/om/om-collect/openlookeng/kustomization.yaml
Add function: get gitee metrics and ranks info
> Add function: get gitee metrics and ranks info

- common-applications/om/om-collect/mindspore/gitee-metrics/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee-metrics/kustomization.yaml
- common-applications/om/om-collect/opengauss/gitee-metrics/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee-metrics/kustomization.yaml
> Update gitee metrics version

- common-applications/om/om-webserver/deployment.yaml
> add update_at for api all

- common-applications/om/om-collect/ascend/gitee-star/kustomization.yaml
- common-applications/om/om-collect/ascend/gitee/kustomization.yaml
- common-applications/om/om-collect/hongmeng/gitee/kustomization.yaml
- common-applications/om/om-collect/kunpeng/gitee/kustomization.yaml
- common-applications/om/om-collect/mindspore/gitee-star/kustomization.yaml
- common-applications/om/om-collect/mindspore/gitee/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee-issue/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee-star/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee/kustomization.yaml
- common-applications/om/om-collect/opengauss/gitee-star/kustomization.yaml
- common-applications/om/om-collect/opengauss/gitee/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee-star/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee/kustomization.yaml
> update company changed user

- common-applications/om/om-collect/kunpeng/blue_zone_user/kustomization.yaml
> strip giteeID and emails

- common-applications/om/om-collect/kunpeng/github_pytorch_pr_issue/kustomization.yaml
- common-applications/om/om-collect/kunpeng/github_spark_pr_issue/kustomization.yaml
- common-applications/om/om-collect/kunpeng/github_tensorflow_pr_issue/kustomization.yaml
check github pr/issue comment has not user
> check github pr/issue comment has not user

- common-applications/om/om-collect/kunpeng/github_pytorch_pr_issue/kustomization.yaml
- common-applications/om/om-collect/kunpeng/github_spark_pr_issue/kustomization.yaml
- common-applications/om/om-collect/kunpeng/github_tensorflow_pr_issue/kustomization.yaml
> change github comments token

- common-applications/om/om-kafka/openeuler/kustomization.yaml
- common-applications/om/om-kafka/openeuler/obs-job-history-recent/deploy.json
- common-applications/om/om-kafka/openeuler/obs-job-history-recent/kustomization.yaml
- common-applications/om/om-kafka/openeuler/obs-job-history-recent/secrets.yaml
- common-applications/om/om-webserver/deployment.yaml
1、add obs-job-history-recent consumer
2、get obs detail from recent data
> add obs-job-history-recent consumer

- common-applications/om/om-webserver/deployment.yaml
if cla query fail then partners is zero
> if cla query fail then partners is zero

- common-applications/om/om-collect/openeuler/kustomization.yaml
- common-applications/om/om-collect/openeuler/sig-radar-score/deploy.json
- common-applications/om/om-collect/openeuler/sig-radar-score/kustomization.yaml
- common-applications/om/om-collect/openeuler/sig-radar-score/secrets.yaml
- common-applications/om/om-collect/openeuler/sig-score/deploy.json
- common-applications/om/om-collect/openeuler/sig-score/kustomization.yaml
- common-applications/om/om-collect/openeuler/sig-score/secrets.yaml
Add sig score and sig radar score service
> Add sig score and sig radar score service

- common-applications/om/om-webserver/deployment.yaml
update sig score/sig radar score API
update company contribute, add param repo for openGauss and param sig for openEuler
> update sig score API, update company contribute API

- common-applications/om/om-webserver/deployment.yaml
change version api branchs to branch_detail
> change version api branchs to branch_detail

- common-applications/om/om-collect/openeuler/sig-radar-score/kustomization.yaml
- common-applications/om/om-collect/openeuler/sig-score/kustomization.yaml
- common-applications/om/om-webserver/deployment.yaml
update track data server/add param community for putUserActionsinfo API
update sig score service/update maintainer calculation
> update om-webserver, update sig score service

- common-applications/om/om-webserver/deployment.yaml
Add API to get company sig relationship, update API sig score/add sig feature
> Add API to get company sig relationship, update API sig score

- common-applications/om/om-webserver/deployment.yaml
Add Authentication for some sig APIs, delete param company for company/sigs API
> Add Authentication for some sig APIs

- common-applications/om/om-collect/openeuler/collect-data/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee-issue-score/kustomization.yaml
- common-applications/om/om-collect/openlookeng/gitee-issue-score/kustomization.yaml
Update collect-data and gitee-issue-score service/Handling when object is NoneType
> Update collect-data and gitee-issue-score service

- common-applications/om/om-collect/openeuler/polymerization-download-ip/kustomization.yaml
- common-applications/om/om-collect/openeuler/up-download-ratio/kustomization.yaml
- common-applications/om/om-collect/opengauss/kustomization.yaml
- common-applications/om/om-collect/opengauss/ndcg/deploy.json
- common-applications/om/om-collect/opengauss/ndcg/kustomization.yaml
- common-applications/om/om-collect/opengauss/ndcg/secrets.yaml
- common-applications/om/om-collect/openlookeng/kustomization.yaml
- common-applications/om/om-collect/openlookeng/ndcg/deploy.json
- common-applications/om/om-collect/openlookeng/ndcg/kustomization.yaml
- common-applications/om/om-collect/openlookeng/ndcg/secrets.yaml
1、add ndcg for opengauss/openlookeng
2、calc openeuler download ip count using cardinality
> add ndcg for opengauss/openlookeng

- common-applications/om/om-collect/openeuler/gitee/kustomization.yaml
> mark invalid pr by title

- common-applications/om/om-webserver/deployment.yaml
get authing user by access token
> get authing user by access token

- common-applications/om/om-webserver/deployment.yaml
add id_token for authing usr permission
> add id_token for authing usr permission

- common-applications/om/om-collect/mindspore/cve/kustomization.yaml
- common-applications/om/om-collect/openeuler/cve/kustomization.yaml
- common-applications/om/om-collect/opengauss/cve/kustomization.yaml
- common-applications/om/om-collect/openlookeng/cve/kustomization.yaml
> add cve versions

- common-applications/om/om-webserver/deployment.yaml
> add used token to blacklist

- common-applications/om/om-collect/openeuler/code-statistics/deployment.yaml
- common-applications/om/om-collect/openeuler/code-statistics/kustomization.yaml
- common-applications/om/om-collect/openeuler/code-statistics/pvc.yaml
- common-applications/om/om-collect/openeuler/code-statistics/secrets.yaml
- common-applications/om/om-collect/openeuler/kustomization.yaml
add code statistics for openeuler
> add code statistics for openeuler

- common-applications/om/om-collect/openeuler/code-statistics/deployment.yaml
> return companies of repo

- common-applications/om/om-collect/openeuler/code-statistics/deployment.yaml
> install cloc for pod

- common-applications/om/om-collect/openeuler/code-statistics/deployment.yaml
> update update_at date format

- common-applications/om/om-collect/openeuler/code-statistics/deployment.yaml
continue other branch when one branch fail
> continue other branch when one branch fail

- common-applications/om/om-collect/openeuler/code-statistics/deployment.yaml
> decompress zip/gz files

- common-applications/om/om-collect/openeuler/cve/kustomization.yaml
change to calc the cve_rec_duration
> change to calc the cve_rec_duration

- common-applications/om/om-collect/openeuler/code-statistics/deployment.yaml
1、wget cloc 1.94
2、git clean when fail
> wget cloc 1.94

- common-applications/om/om-collect/openeuler/cve/kustomization.yaml
> format cve public time

- common-applications/om/om-webserver/deployment.yaml
check authing user login status
> check authing user login status

- common-applications/om/om-collect/openeuler/git-commit-log/deployment.yaml
> add sig names for commit

- common-applications/om/om-collect/openeuler/git-commit-log/deployment.yaml
> change sig_names to list

- common-applications/control/mail/config.yaml
- common-applications/control/mail/mtaservice.yaml
Reverts opensourceways/infra-common#804
> Revert "update exim version 4.95"

- common-applications/om/om-webserver/deployment.yaml
change authing logout api to check AuthingUserToken
> change authing logout api to check AuthingUserToken

- common-applications/om/om-webserver/deployment.yaml
add user photo when token creating
> add user photo when token creating

- common-applications/om/om-collect/openeuler/gitee/kustomization.yaml
add package_name for repo`s branch
> add package_name for repo`s branch

- common-applications/om/om-collect/openeuler/kustomization.yaml
- common-applications/om/om-collect/openeuler/rpm-repo-download/deploy.json
- common-applications/om/om-collect/openeuler/rpm-repo-download/kustomization.yaml
- common-applications/om/om-collect/openeuler/rpm-repo-download/secrets.yaml
> add repo download from rpm

- common-applications/om/om-collect/openeuler/rpm-repo-download/kustomization.yaml
add task that repo download from rpm
> add task that repo download from rpm

- common-applications/om/om-collect/openeuler/rpm-repo-download/kustomization.yaml
> install rsync

- common-applications/om/om-webserver/deployment.yaml
set redirect url when getting authing accessToken by code
> set redirect url when getting authing accessToken by code

- common-applications/om/om-collect/openeuler/rpm-repo-download/kustomization.yaml
change package version to lower case
> change package version to lower case

- common-applications/om/om-webserver/deployment.yaml
1、get company name yaml to local
2、check velue when write to redis
3、return authing user name
> get company name yaml to local

- common-applications/om/om-webserver/deployment.yaml
1、push track data into kafka
2、decode url parameter
> push track data into kafka

- common-applications/om/om-kafka/openeuler/community-tracker/deploy.json
- common-applications/om/om-kafka/openeuler/community-tracker/kustomization.yaml
- common-applications/om/om-kafka/openeuler/community-tracker/secrets.yaml
- common-applications/om/om-kafka/openeuler/kustomization.yaml
> add track data to kafka

- common-applications/om/om-webserver/deployment.yaml
do not check code when redis setting authing token
> do not check code when redis setting authing token

- common-applications/om/om-webserver/deployment.yaml
add isoftstone when statistic company contributors
> add isoftstone when statistic company contributors

- common-applications/om/om-collect/kunpeng/blue_zone_user/kustomization.yaml
- common-applications/om/om-webserver/deployment.yaml
add multiple emails for blue user
> add multiple emails for blue user

- common-applications/om/om-collect/kunpeng/git-commit-log-enterprise/deployment.yaml
- common-applications/om/om-collect/kunpeng/git-commit-log-enterprise/kustomization.yaml
- common-applications/om/om-collect/kunpeng/git-commit-log-enterprise/pvc.yaml
- common-applications/om/om-collect/kunpeng/git-commit-log-enterprise/secrets.yaml
- common-applications/om/om-collect/kunpeng/gitee/kustomization.yaml
- common-applications/om/om-collect/kunpeng/kustomization.yaml
add kunpeng-dpu data collection
> add kunpeng-dpu data collection

- common-applications/om/om-collect/openeuler/prophet_prediction/deployment.yaml
- common-applications/om/om-collect/openeuler/prophet_prediction/kustomization.yaml
continue next user when action event is null
> continue next user when action event is null

- common-applications/om/om-collect/ascend/git-commit-log-enterprise/deployment.yaml
- common-applications/om/om-collect/ascend/git-commit-log-enterprise/kustomization.yaml
- common-applications/om/om-collect/ascend/git-commit-log-enterprise/pvc.yaml
- common-applications/om/om-collect/ascend/git-commit-log-enterprise/secrets.yaml
- common-applications/om/om-collect/ascend/gitee-enterprise/deploy.json
- common-applications/om/om-collect/ascend/gitee-enterprise/kustomization.yaml
- common-applications/om/om-collect/ascend/gitee-enterprise/secrets.yaml
- common-applications/om/om-collect/ascend/kustomization.yaml
add enterprise owner data of ascend
> add enterprise owner data of ascend

- common-applications/om/om-webserver/deployment.yaml
1、add phone and email code for unbind account
2、add getting connection list
> add phone and email code for unbind account

- common-applications/om/om-webserver/deployment.yaml
> add request error info

- common-applications/om/om-webserver/deployment.yaml
1、add cookie
2、verify domain
3、encrypt token
> update authing interceptor

- common-applications/om/om-webserver/deployment.yaml
unlink multiple identity sources for gitee
> unlink multiple identity sources for gitee

- common-applications/om/om-webserver/deployment.yaml
https://gitee.com/opensourceway/om-webserver/commit/68583d51c7ebab945d36d63b1b8c37c95e37d1b7
> logout and delete cookie

- common-applications/om/om-collect/kunpeng/blue_zone_user/kustomization.yaml
- common-applications/om/om-collect/kunpeng/github_pr_issue/kustomization.yaml
> add fields for blue zone user

- common-applications/om/om-collect/kunpeng/github_pr_issue/kustomization.yaml
> revert commit id to id

- common-applications/test-environment/om-webserver/deployment.yaml
- common-applications/test-environment/om-webserver/ingress.yaml
- common-applications/test-environment/om-webserver/kustomization.yaml
- common-applications/test-environment/om-webserver/secrets.yaml
- common-applications/test-environment/om-webserver/service.yaml
add test environment of om-webserver
> add test environment of om-webserver

- common-applications/om/om-webserver/deployment.yaml
- common-applications/test-environment/om-webserver/deployment.yaml
add email/phone register and login
> add email/phone register and login

- common-applications/om/om-webserver/deployment.yaml
- common-applications/test-environment/om-webserver/deployment.yaml
> update username api

- common-applications/test-environment/om-webserver/deployment.yaml
> add login fail count limit

- common-applications/om/om-webserver-test/deployment.yaml
> change Random to SecureRandom

- common-applications/om/om-collect/mindspore/cve/kustomization.yaml
- common-applications/om/om-collect/openeuler/cve/kustomization.yaml
- common-applications/om/om-collect/opengauss/cve/kustomization.yaml
- common-applications/om/om-collect/openlookeng/cve/kustomization.yaml
> CVE_public_time data format

- common-applications/om/om-webserver-test/deployment.yaml
delete user`s old photo when update photo
> delete user`s old photo when update photo

- common-applications/om/om-webserver-test/deployment.yaml
- common-applications/om/om-webserver/deployment.yaml
delete openeuler`s default contributors
> delete openeuler`s default contributors

- common-applications/om/om-webserver-test/deployment.yaml
> add email exist when login

- common-applications/om/om-webserver-test/deployment.yaml
> add odic authorize/token/user

- common-applications/om/om-webserver-test/deployment.yaml
scope must contains openid and profile
> scope must contains openid and profile

- common-applications/om/om-webserver-test/deployment.yaml
change oidc authorize、token、user parameter
> change oidc authorize、token、user parameter

- common-applications/om/om-webserver-test/deployment.yaml
add login and logout for opengauss
> add login and logout for opengauss

- common-applications/om/om-webserver-test/deployment.yaml
> update webserver-test  to remove alibaba.fastjson

- common-applications/om/om-webserver-test/deployment.yaml
add update/bind/unbind for opengauss
> add update/bind/unbind for opengauss

- common-applications/om/om-webserver-test/deployment.yaml
update username/nickname to lower case
> update username/nickname to lower case

- common-applications/om/om-webserver-test/deployment.yaml
update send code channel to register and other
> update send code channel to register and other

- common-applications/om/om-webserver-test/deployment.yaml
add login error count when code error
> add login error count when code error

- common-applications/om/om-webserver-test/deployment.yaml
add msg that phone/email bind by other user
> add msg that phone/email bind by other user

- common-applications/om/om-webserver-test/deployment.yaml
> allow nickname to be empty

- common-applications/om/om-webserver-test/deployment.yaml
> add register code error count

- common-applications/om/om-collect/ascend/gitee/kustomization.yaml
some repos failed to fetch data
> some repos failed to fetch data

- common-applications/om/om-collect/openeuler/polymerization-download-ip/kustomization.yaml
- common-applications/om/om-collect/openeuler/up-download-ratio/kustomization.yaml
update image version that old one has been deleted
> update image version that old one has been deleted

- common-applications/om/om-webserver-test/deployment.yaml
> add identities for oidc

- common-applications/om/om-webserver-test/deployment.yaml
add link and unlink of openatom
> add link and unlink of openatom

- common-applications/om/om-webserver-test/deployment.yaml
update username/loginname of openatom
> update username/loginname of openatom

- common-applications/om/om-webserver-test/deployment.yaml
update username that username startsWith oauth2
> update username that username startsWith oauth2

- common-applications/om/datastat-server/deployment.yaml
- common-applications/om/datastat-server/ingress.yaml
- common-applications/om/datastat-server/kustomization.yaml
- common-applications/om/datastat-server/namespace.yaml
- common-applications/om/datastat-server/secrets.yaml
- common-applications/om/datastat-server/service.yaml
> add datastat api server

- common-applications/om/datastat-server/deployment.yaml
- common-applications/om/om-webserver-test/deployment.yaml
1、add email for user/refresh
2、parse oidc/token request header
> add email for user/refresh

- common-applications/om/om-webserver-test/deployment.yaml
> parse email from mysql

- common-applications/om/datastat-server/deployment.yaml
> gitee webhook test

- common-applications/om/datastat-server/deployment.yaml
- common-applications/om/om-webserver-test/deployment.yaml
1、parse gitee webhook user
2、update result of oidc/user
> update result of oidc/user

- common-applications/om/datastat-server/secrets.yaml
change name of custom_properties
> change name of custom_properties

- common-applications/om/datastat-server/deployment.yaml
> gitee action webhook

- common-applications/om/om-collect/mindspore/account_org/kustomization.yaml
- common-applications/om/om-collect/openeuler/account_org/kustomization.yaml
- common-applications/om/om-collect/openeuler/gitee_developer/kustomization.yaml
- common-applications/om/om-collect/opengauss/account_org/kustomization.yaml
> update id of account

- common-applications/om/om-webserver-xihe/deployment.yaml
- common-applications/om/om-webserver-xihe/ingress.yaml
- common-applications/om/om-webserver-xihe/kustomization.yaml
- common-applications/om/om-webserver-xihe/namespace.yaml
- common-applications/om/om-webserver-xihe/secrets.yaml
- common-applications/om/om-webserver-xihe/service.yaml
> add om-webserver for xihe

- common-applications/om/om-webserver-test/deployment.yaml
stay logged in and refresh token when user has interaction
> stay logged in and refresh token when user has interaction

- common-applications/om/om-webserver-test/deployment.yaml
> add app manage

- common-applications/om/om-webserver-test/deployment.yaml
change email template to English
> change email template to English

- common-applications/om/om-webserver/deployment.yaml
add email register for openGauss
> add email register for openGauss

- common-applications/om/om-webserver-test/deployment.yaml
- common-applications/om/om-webserver/deployment.yaml
delete blank space of email template
> delete blank space of email template

- common-applications/om/om-webserver-test/deployment.yaml
> change login error message

- common-applications/om/om-webserver-provider/deployment.yaml
- common-applications/om/om-webserver-provider/ingress.yaml
- common-applications/om/om-webserver-provider/kustomization.yaml
- common-applications/om/om-webserver-provider/namespace.yaml
- common-applications/om/om-webserver-provider/secrets.yaml
- common-applications/om/om-webserver-provider/service.yaml
- common-applications/om/om-webserver-xihe-test/deployment.yaml
- common-applications/om/om-webserver-xihe-test/ingress.yaml
- common-applications/om/om-webserver-xihe-test/kustomization.yaml
- common-applications/om/om-webserver-xihe-test/namespace.yaml
- common-applications/om/om-webserver-xihe-test/secrets.yaml
- common-applications/om/om-webserver-xihe-test/service.yaml
> add xihe api test

- common-applications/om/om-webserver-test/deployment.yaml
> remove get user from mysql

- common-applications/om/om-webserver-test/deployment.yaml
- common-applications/om/om-webserver-test/secrets.yaml
> remove query api

- common-applications/om/om-webserver-oneid/deployment.yaml
- common-applications/om/om-webserver-oneid/ingress.yaml
- common-applications/om/om-webserver-oneid/kustomization.yaml
- common-applications/om/om-webserver-oneid/namespace.yaml
- common-applications/om/om-webserver-oneid/secrets.yaml
- common-applications/om/om-webserver-oneid/service.yaml
> add oneid api server

- common-applications/om/om-webserver-test/deployment.yaml
register and login by password
> register and login by password

- common-applications/om/om-webserver-test/deployment.yaml
register and login by password for openGauss
> register and login by password for openGauss

- common-applications/om/om-collect/kunpeng/gitee_github_combine/kustomization.yaml
add pr/issue count for open-source
> add pr/issue count for open-source

- common-applications/om/om-webserver-test/deployment.yaml
add channel register_by_password for opengauss
> add channel register_by_password for opengauss

- common-applications/om/om-webserver-test/deployment.yaml
> get manager token from redis

- common-applications/om/om-webserver-test/deployment.yaml
> login by username+password

- common-applications/om/om-webserver-test/deployment.yaml
send message that "Invalid account or password" when login fail by password
> send message that "Invalid account or password" when login fail by password

- common-applications/om/om-webserver-test/deployment.yaml
> add captcha limit for login

- common-applications/om/om-webserver-test/deployment.yaml
> add id for jwt

- common-applications/om/om-webserver-test/deployment.yaml
change /captcha/checkLogin to GET
> change /captcha/checkLogin to GET

- common-applications/om/om-webserver-test/deployment.yaml
add interceptor before send code
> add interceptor before send code

- common-applications/test-environment/openeuler-website-docs/ingress.yaml
- common-applications/test-environment/openeuler-website/ingress.yaml
- common-applications/test-environment/opengauss-website-docs/ingress.yaml
- common-applications/test-environment/openlookeng-website-docs/ingress.yaml
- openEuler、openGauss、openLookeng 文档测试环境新增常规 http 安全响应头
- openEuler 官网测试环境新增 飞书 iframe
> update docs repo http header

- common-applications/om/datastat-server/deployment.yaml
更改datastat-server的maven源为国内源,成功打包镜像。
> update datastat-server:change maven source

- common-applications/om/datastat-server/deployment.yaml
https://github.com/opensourceways/datastat-server/pull/122
try second to fit the api /score
> update datastat 

- common-applications/om/datastat-server/deployment.yaml
https://github.com/opensourceways/datastat-server/pull/130
> update datastat-server to change base image of dockerfile from ubuntu to openeuler

- common-applications/om/datastat-server/deployment.yaml
https://github.com/opensourceways/datastat-server/pull/157
> update datastat-server image

- common-applications/om/datastat-server/deployment.yaml
https://github.com/opensourceways/datastat-server/pull/158
> update datastat-server to fix bug of buildCheckInfo

- common-applications/test-environment/merlin/space/deployment.yaml
> Update space deployment.yaml
